language: rust

# Need to cache the whole `.cargo` directory to keep .crates.toml for
# cargo-update to work
#
cache:
  directories:
    - /home/travis/.cargo

# But don't cache the cargo registry
# and remove wasm-pack binary to avoid the installer asking confirmation for overwriting it.
#
before_cache:
  - rm -rf /home/travis/.cargo/git
  - rm -rf /home/travis/.cargo/registry
  - rm -rf /home/travis/.cargo/bin/cargo-tarpaulin
  - rm -rf target/debug/incremental/{futures_ringbuf,build_script_build}-*
  - rm -rf target/debug/.fingerprint/futures_ringbuf-*
  - rm -rf target/debug/build/futures_ringbuf-*
  - rm -rf target/debug/deps/libfutures_ringbuf-*
  - rm -rf target/debug/deps/futures_ringbuf-*
  - rm -rf target/debug/{futures_ringbuf,libfutures_ringbuf}.d
  - cargo clean -p futures_ringbuf


branches:
  only:
    - master
    - dev

jobs:

  include:

    - name  : linux stable check
      os    : linux
      rust  : stable
      script: cargo check


    - name  : linux nightly test everything
      os    : linux
      dist  : bionic
      rust  : nightly

      addons:
        firefox: latest
        apt:
          packages:
            - libssl-dev         # for cargo-tarpaulin
            - libgtk-3-dev       # needed for headless (sic) firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1372998
            - libdbus-glib-1-dev # firefox

      # for wasm tests
      #
      install:
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      script:
        - bash ci/check.bash
        - bash ci/test.bash
        - bash ci/doc.bash
        - bash ci/wasm.bash
        - bash ci/deny.bash
        - bash ci/coverage.bash


    - os    : osx
      script:
        - bash ci/test.bash


    - os    : windows
      script:
        - bash ci/test.bash


